runtime : nodejs10

instance_class: F2

env_variables:
  BUCKET_NAME: "getfix-bucket1"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto